#include "Mysybmol.c"

#define MYSYBMOL_SERIAL_DISPLAY "\uE60A"
#define MYSYBMOL_NO_WIFI "\uE632"
#define MYSYBMOL_CALIBRATION "\uE61E"
#define MYSYBMOL_GAME "\uE8A7"
#define MYSYBMOL_IMAGE_TRAN "\uE603"